import { build } from 'esbuild';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
const qa=process.argv.includes('--qa');
const desktop=process.argv.includes('--desktop');
const outputDir=qa?'qa-preview':desktop?'desktop-dist':'preview';
await mkdir(outputDir,{recursive:true});
const result = await build({entryPoints:['main.js'],define:{__QA__:String(qa)},bundle:true,minify:true,format:'iife',write:false,legalComments:'inline',loader:{'.mp3':'dataurl'}});
const template = await readFile('template.html','utf8');
const license = await readFile('THREE-LICENSE.txt','utf8');
const output=template.replace('/* SCENE_BUNDLE */', () => result.outputFiles[0].text.replaceAll('</script','<\\/script'));
await writeFile(`${outputDir}/index.html`,(output+'\n<!-- Three.js license\n'+license+'\n-->\n').replace(/[\t ]+$/gm,''));
console.log(`Built ${outputDir}/index.html — all JavaScript bundled, no CDN required.`);
