import journalCover from '../assets/journal-cover.png';
import {createShipPreview} from './ship-preview.mjs';
import {createShipPages,element,JOURNAL_START_PAGE} from './ship-pages.mjs';
import {paginateJournal,renderBlock} from './pages.mjs';
import {PencilAudioController,createWritingAnimator,wait} from './writing.mjs';

export const JournalBookState=Object.freeze({CLOSED:'closed',OPENING:'opening',OPEN:'open',WRITING:'writing',DRAWING:'drawing',FLIPPING:'flipping',CLOSING:'closing'});
export function JournalBookController({renderer,ship,controls,customization,skins,accessories,badges,journal,intents,store,sailing,audioAllowed,onEnter,onLeave}){
 const root=document.querySelector('#journal'),book=root.querySelector('.journal-book'),left=root.querySelector('.left-page'),right=root.querySelector('.right-page'),flip=root.querySelector('.flip-page'),spread=root.querySelector('.book-spread'),entry=root.querySelector('#journal-open'),dock=root.querySelector('.journal-dock'),closeButton=root.querySelector('#journal-close');
 const measure=document.querySelector('.journal-measure'),reduced=matchMedia('(prefers-reduced-motion: reduce)'),preview=createShipPreview(renderer,ship),audio=PencilAudioController(audioAllowed),writer=createWritingAnimator(document.querySelector('#journal-pencil'),audio,reduced);
 let phase='closed',index=0,pages=[],pending=null,queuedClose=false,dirty=false,scheduled=false,savedControls=false,previousFocus=null,dockRect=null,badgeSignature='',pageSize='',pageRevision=-1;
 const shipPages=createShipPages({store,sailing,customization,skins,accessories,badges,journal,intents,preview,changed(rebuild=true,redraw=false){if(rebuild)preview.rebuild();cover();for(const label of root.querySelectorAll('.model-name'))label.textContent=customization.data.name;if(rebuild||redraw)render();}});
 const duration=ms=>reduced.matches?70:ms;
 function setState(value){phase=value;root.dataset.state=value;if(value!=='open'&&value!=='closed'&&root.contains(document.activeElement))closeButton.focus();navigation();}
 function cover(){const notice=journal.notice();root.classList.toggle('has-unread',notice.kind!=='none');root.classList.toggle('has-clue',notice.kind==='clue');root.dataset.notice=notice.kind;const marker=root.querySelector('#journal-unread');marker.hidden=notice.kind==='none';marker.textContent=notice.kind==='clue'?'…':'';const hint=notice.kind==='clue'?'有一段航行，等你续写':notice.kind==='record'?'有一篇值得记住的新见闻':'航海日志';entry.setAttribute('aria-label',customization.data.name+'的航海手账，'+hint);entry.title=hint;root.querySelector('.journal-dock-label').textContent=hint;const tab=root.querySelector('[data-chapter=voyage]');tab.textContent='航海日志';tab.setAttribute('aria-label',hint+'，翻到航海记录');tab.title=hint;}

 function layout(){
  const w=book.offsetWidth,h=book.offsetHeight,d=dock.getBoundingClientRect(),scale=d.width/(w/2+3);dock.style.height=(h+8)*scale+'px';const rect=dock.getBoundingClientRect();
  book.style.setProperty('--dock-x',(rect.left-book.offsetLeft-w/2*scale)+'px');book.style.setProperty('--dock-y',(rect.top-book.offsetTop)+'px');book.style.setProperty('--dock-sx',scale);book.style.setProperty('--dock-sy',scale);
  root.style.setProperty('--dock-label-x',rect.left+'px');root.style.setProperty('--dock-label-y',(rect.bottom+10)+'px');measure.style.width=w/2+'px';measure.style.height=h+'px';
 }
 function rebuildPages(){layout();const size=measure.style.width+':'+measure.style.height;if(pages.length&&!dirty&&pageSize===size&&pageRevision===journal.revision)return;pageSize=size;pageRevision=journal.revision;pages=[...Array(JOURNAL_START_PAGE).fill(null),...paginateJournal(journal.entries(),journal.annotations(),measure.querySelector('.journal-content'))];if(pages.length%2)pages.push([]);index=Math.min(index,pages.length-2);dirty=false;}
 function paint(page,at){page.replaceChildren();page.classList.remove('has-intent');const content=element('div','journal-content');if(at<JOURNAL_START_PAGE)shipPages.render(at,content);else for(const block of pages[at]??[]){const node=renderBlock(block,choose);if(pending?.id===block.entry?.id){if(block.kind==='written'&&!pending.written.has(block.key))node.style.visibility='hidden';if(block.kind==='doodle'&&!pending.drawn)node.style.visibility='hidden';}content.append(node);}page.append(content,element('span','journal-folio',String(at+1).padStart(2,'0')));}
 function copyPage(source,target){target.replaceChildren(...[...source.childNodes].map(n=>n.cloneNode(true)));const originals=source.querySelectorAll('canvas');target.querySelectorAll('canvas').forEach((c,i)=>c.getContext('2d')?.drawImage(originals[i],0,0));target.querySelectorAll('[id]').forEach(n=>n.removeAttribute('id'));target.inert=true;}
 function prepareCover(){const back=root.querySelector('.cover-back');back.replaceChildren();const page=element('div','journal-page cover-inside');copyPage(left,page);back.append(page);}
 function read(includeClues=false){const ids=[...(pages[index]??[]),...(pages[index+1]??[])].filter(b=>b.end).map(b=>b.entry.id);journal.markReadIds(ids,includeClues);}
 function render(){const focused=document.activeElement,selector=['data-skin','data-accessory','data-badge'].find(a=>focused?.hasAttribute(a)),value=selector?focused.getAttribute(selector):null,refocus=left.contains(focused)||right.contains(focused);preview.bind(null);paint(left,index);paint(right,index+1);navigation();if(refocus)(selector?[...root.querySelectorAll('['+selector+']')].find(n=>n.getAttribute(selector)===value):closeButton)?.focus();if(phase==='open'){journal.remember(index,index<JOURNAL_START_PAGE?(index===4?'objects':'ship'):'voyage');read();}}
 function voyagePage(){const entries=journal.entries(),id=journal.notice().entryId??(entries.find(e=>!e.read)??entries.at(-1))?.id,at=pages.findIndex(p=>p?.some(b=>b.entry?.id===id));return at<JOURNAL_START_PAGE?JOURNAL_START_PAGE:at-at%2;}
 function navigation(){const locked=phase!=='open';root.querySelectorAll('#journal-prev,.journal-prev').forEach(b=>b.disabled=locked||index===0);root.querySelectorAll('#journal-next,.journal-next').forEach(b=>b.disabled=locked||index+2>=pages.length);root.querySelectorAll('[data-chapter]').forEach(b=>{b.disabled=locked;const current=b.dataset.chapter===(index>=JOURNAL_START_PAGE?'voyage':index===4?'objects':'ship');if(current)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});document.querySelector('#journal-page-number').textContent=(index+1)+' — '+(index+2)+' / '+Math.max(JOURNAL_START_PAGE+2,pages.length);}
 async function open({entryId=null,latest=false}={}){
  if(phase!=='closed')return;previousFocus=document.activeElement;savedControls=controls.enabled;controls.enabled=false;queuedClose=false;layout();dockRect=entry.getBoundingClientRect().toJSON();cover();rebuildPages();index=voyagePage();
  if(entryId||latest){const id=entryId??journal.entries().at(-1)?.id,found=pages.findIndex(p=>p?.some(b=>b.entry?.id===id));index=found<0?JOURNAL_START_PAGE:found-found%2;}
  setState('opening');root.setAttribute('role','dialog');root.setAttribute('aria-modal','true');document.body.dataset.journal='true';root.classList.add('is-opening');root.classList.remove('is-closing');render();prepareCover();onEnter();void book.offsetWidth;root.classList.add('is-open');entry.inert=true;closeButton.focus();audio.paper('page');await wait(duration(1050));root.classList.remove('is-opening');root.querySelector('.cover-back').replaceChildren();setState('open');render();if(queuedClose)void close();
 }
 async function close(){
  if(phase==='closed'||phase==='closing')return;if(phase!=='open'){queuedClose=true;return;}read(true);prepareCover();queuedClose=false;setState('closing');preview.bind(null);audio.stopStroke();audio.paper('close');layout();root.classList.add('is-closing');await wait(duration(900));root.classList.remove('is-open','is-opening','is-closing');document.body.dataset.journal='false';root.setAttribute('role','group');root.removeAttribute('aria-modal');entry.inert=false;root.querySelector('.cover-back').replaceChildren();setState('closed');controls.enabled=savedControls;onLeave();cover();(previousFocus?.isConnected&&previousFocus!==document.body&&getComputedStyle(previousFocus).visibility==='visible'?previousFocus:entry).focus();
 }
 async function flipTo(target,ms=620){
  target=Math.max(0,Math.min(pages.length-2,target-target%2));const forward=target>=index,front=flip.querySelector('.page-front'),back=flip.querySelector('.page-back');preview.bind(null);
  copyPage(forward?right:left,front);paint(back,forward?target:target+1);paint(forward?right:left,forward?target+1:target);preview.bind(null);
  flip.hidden=false;flip.className='flip-page';spread.style.setProperty('--flip-duration',duration(ms)+'ms');spread.classList.add('turning');
  await new Promise(requestAnimationFrame);flip.classList.add(forward?'next':'prev');audio.paper('page');
  const animation=flip.getAnimations().find(a=>a.animationName===(forward?'journal-next':'journal-prev'));
  if(animation)await animation.finished.catch(()=>{});else await wait(duration(ms));
  (forward?left:right).replaceChildren(...back.childNodes);index=target;flip.hidden=true;flip.className='flip-page';front.replaceChildren();spread.classList.remove('turning');preview.bind(right.querySelector('.journal-ship-model'));navigation();
 }
 async function turn(target,chapter=false){if(phase!=='open'||target===index||target<0||target>=pages.length)return;setState('flipping');await flipTo(target,chapter?700:620);setState('open');if(dirty){rebuildPages();render();}else{journal.remember(index,index<JOURNAL_START_PAGE?(index===4?'objects':'ship'):'voyage');read();}if(queuedClose)void close();}
 async function choose(entry,option,node){
  if(phase!=='open')return;setState('writing');pending={id:entry.id,written:new Set(),drawn:false};const result=journal.selectIntent(entry.id,option.id);if(result!=='selected'){pending=null;setState('open');document.querySelector('#ship-notice').textContent='这句话还没能保存，请稍后再写。';return;}
  node.closest('.journal-content').classList.add('intent-writing');await wait(duration(250));rebuildPages();render();
  try{
   for(let at=JOURNAL_START_PAGE;at<pages.length;at++)for(const block of pages[at])if(block.entry?.id===entry.id&&block.kind==='written'){
    if(at-at%2!==index){setState('flipping');await flipTo(at);setState('writing');}const page=at%2?right:left,el=[...page.querySelectorAll('[data-block]')].find(n=>n.dataset.block===block.key);el.style.visibility='visible';await writer.writeText(el,block.text);pending.written.add(block.key);
   }
   const at=pages.findIndex(p=>p?.some(b=>b.entry?.id===entry.id&&b.kind==='doodle'));if(at>=JOURNAL_START_PAGE){if(at-at%2!==index){setState('flipping');await flipTo(at);}setState('drawing');const el=[...(at%2?right:left).querySelectorAll('[data-kind=doodle]')].find(n=>n.dataset.entry===entry.id);el.style.visibility='visible';await writer.draw(el);pending.drawn=true;}
  }finally{audio.stopStroke();document.querySelector('#journal-pencil').setAttribute('hidden','');pending=null;setState('open');if(dirty)rebuildPages();render();if(queuedClose)void close();}
 }
 root.querySelector('.journal-backdrop').onclick=()=>void close();closeButton.onclick=()=>void close();entry.onclick=()=>void open();root.querySelectorAll('#journal-prev,.journal-prev').forEach(b=>b.onclick=()=>void turn(index-2));root.querySelectorAll('#journal-next,.journal-next').forEach(b=>b.onclick=()=>void turn(index+2));root.querySelectorAll('[data-chapter]').forEach(b=>b.onclick=()=>void turn(b.dataset.chapter==='ship'?0:b.dataset.chapter==='objects'?4:voyagePage(),true));
 root.querySelector('.journal-dock-label').onclick=()=>void open();
 document.addEventListener('pointerdown',e=>{if(!e.target.closest('.paper-mileage')){const info=document.querySelector('.mileage-note');if(info)info.hidden=true;document.querySelector('#ship-balance')?.setAttribute('aria-expanded','false');}});
 document.addEventListener('keydown',e=>{if(phase==='closed'||e.isComposing)return;if(e.key==='Escape'){if(e.target.matches('input'))return;e.preventDefault();e.stopPropagation();void close();}if(e.target.matches('input,select,canvas'))return;
  if(e.key==='ArrowRight'||e.key==='PageDown'){e.preventDefault();void turn(index+2);}if(e.key==='ArrowLeft'||e.key==='PageUp'){e.preventDefault();void turn(index-2);}if(e.key==='Tab'){const list=[...root.querySelectorAll('button:not(:disabled),input,select,canvas[tabindex]')].filter(el=>!el.closest('[inert]')&&el.getClientRects().length&&getComputedStyle(el).visibility==='visible'),at=list.indexOf(document.activeElement);e.preventDefault();list[(at+(e.shiftKey?-1:1)+list.length)%list.length]?.focus();}
 });
 journal.subscribe(()=>{cover();if(pageRevision===journal.revision)return;dirty=true;if(scheduled)return;scheduled=true;queueMicrotask(()=>{scheduled=false;if(phase==='open'&&index>=JOURNAL_START_PAGE){rebuildPages();render();}});});
 window.addEventListener('resize',()=>{layout();if(phase==='open'){rebuildPages();render();}else dirty=true;});document.addEventListener('visibilitychange',audio.sync);window.addEventListener('pagehide',audio.sync);window.addEventListener('beforeunload',()=>{audio.dispose();preview.dispose();});
 root.querySelector('#journal-cover-art').setAttribute('href',journalCover);
 layout();cover();setState('closed');
 return {open,close,openJournal:id=>open({entryId:id,latest:true}),hit:()=>false,noteHit(x,y){return phase==='closed'&&[entry,...(journal.notice().kind!=='none'?[root.querySelector('.journal-dock-label')]:[])].some(n=>{const r=n.getBoundingClientRect();return getComputedStyle(n).visibility==='visible'&&x>=r.left&&x<=r.right&&y>=r.top&&y<=r.bottom;});},refreshBalance:shipPages.refreshBalance,refreshAccessories(){cover();if(phase==='open'&&index===4)render();},refreshBadges(){const signature=customization.data.equippedBadge+':'+badges.views().filter(b=>b.owned).map(b=>b.id).join(',');if(signature===badgeSignature)return;badgeSignature=signature;cover();if(phase==='open'&&index===4)render();},get busy(){return phase!=='closed';},get blend(){return 0;},update(){audio.sync();},renderPreview(now){if((phase==='open'||phase==='opening')&&index<JOURNAL_START_PAGE)preview.render(now);},snapshot:()=>({phase,page:index+1,pages:pages.length,queuedClose,dockRect,preview:preview.snapshot()})};
}
