const {chromium}=require('playwright'),{build}=require('esbuild'),fs=require('node:fs/promises'),path=require('node:path');
// Render the production models in a neutral studio, without a second runtime renderer.
(async()=>{
 const result=await build({stdin:{contents:`
 import * as THREE from 'three';
 import {createBoatModel} from './boat-model.mjs';
 import {createBoatAccessories,DEFAULT_ACCESSORIES,accessoryCatalog} from './boat-accessories.mjs';
 import {createShipCustomization} from './ship-customization.mjs';
 const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setSize(1200,900);renderer.setPixelRatio(1);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.setClearColor('#edf2f3');renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;document.body.append(renderer.domElement);
 const scene=new THREE.Scene(),camera=new THREE.OrthographicCamera(-2.5,2.5,1.875,-1.875,.1,50);scene.add(new THREE.HemisphereLight('#fff6df','#8696aa',2.3));const sun=new THREE.DirectionalLight('#fff2db',3.1);sun.position.set(-3,7,5);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-4;sun.shadow.camera.right=4;sun.shadow.camera.top=4;sun.shadow.camera.bottom=-4;sun.shadow.normalBias=.02;scene.add(sun);scene.add(new THREE.AmbientLight('#e4f0ff',.4));
 const ground=new THREE.Mesh(new THREE.PlaneGeometry(30,30),new THREE.MeshStandardMaterial({color:'#edf2f3',roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-.145;ground.receiveShadow=true;scene.add(ground);
 const boat=createBoatModel();boat.materials.glass.emissiveIntensity=0;scene.add(boat.ship);const custom=createShipCustomization(boat.ship,boat.materials,()=>{},{name:'晚风号'},()=>true,boat);
 window.review=(skin,items={},view='hero')=>{custom.update({skinId:skin,accessories:{...DEFAULT_ACCESSORIES,deck:'lighthouse',roof:'plant',charm:'dolphin-charm',...items}},{save:false});custom.animate(0);boat.ship.position.set(0,0,0);camera.position.set(...(view==='top'?[0,9,.001]:view==='side'?[-7,1.2,0]:[-4.5,3.1,5.2]));camera.lookAt(0,.95,0);camera.zoom=view==='top'?1.18:1.06;camera.updateProjectionMatrix();renderer.render(scene,camera);return renderer.info.memory;};
 window.gallery=()=>{
  boat.ship.visible=false;ground.visible=false;const items=accessoryCatalog.filter(a=>!a.id.startsWith('plate-')&&a.id!=='chimney-skin'),models=[];renderer.setSize(1440,1080);renderer.setScissorTest(true);
  items.forEach((item,i)=>{const model=createBoatModel(),fittings=createBoatAccessories(model),slot=item.slots[0];fittings.apply({...DEFAULT_ACCESSORIES,[slot]:item.id});const source=model.mounts[slot].children[0],group=source.clone(true);group.position.set(0,0,0);group.rotation.set(0,0,0);group.scale.setScalar(1);scene.add(group);const bounds=new THREE.Box3().setFromObject(group),center=bounds.getCenter(new THREE.Vector3()),size=bounds.getSize(new THREE.Vector3());group.position.sub(center);const extent=Math.max(size.x,size.y,size.z)*.75;camera.left=-extent;camera.right=extent;camera.top=extent*.75;camera.bottom=-extent*.75;camera.zoom=1;camera.position.set(2,1.2,5);camera.lookAt(0,0,0);camera.updateProjectionMatrix();const x=i%6*240,y=1080-(Math.floor(i/6)+1)*180;renderer.setViewport(x,y,240,180);renderer.setScissor(x,y,240,180);renderer.setClearColor(i%2?'#edf2f3':'#f7f7f1');renderer.render(scene,camera);group.visible=false;models.push(model);});
  return items.map(i=>i.name);
 };
 window.review('classic');`,resolveDir:process.cwd(),sourcefile:'model-review-entry.js'},bundle:true,format:'iife',write:false});
 const file=path.resolve('qa/model-review.html');await fs.writeFile(file,'<!doctype html><meta charset="utf-8"><style>body{margin:0}canvas{display:block}</style><body><script>'+result.outputFiles[0].text.replaceAll('</script','<\\/script')+'</script>');
 const browser=await chromium.launch({channel:'msedge',headless:true});try{const page=await browser.newPage({viewport:{width:1200,height:900}}),errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error(e.message)});await page.goto('file:///'+file.replaceAll('\\','/'));if(errors.length)throw Error(errors.join('\n'));await page.waitForFunction(()=>window.review);for(const view of ['hero','side','top']){await page.evaluate(v=>window.review('classic',{},v),view);await page.screenshot({path:'qa/remodel-'+view+'.png'});}await page.setViewportSize({width:1440,height:1080});const names=await page.evaluate(()=>window.gallery());await page.screenshot({path:'qa/remodel-accessories.png'});if(errors.length)throw Error(errors.join('\n'));console.log(JSON.stringify({rendered:36,order:names,errors}));}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
