const {chromium}=require('playwright'),{build}=require('esbuild'),fs=require('node:fs/promises'),path=require('node:path');
// Render the production models in a neutral studio, without a second runtime renderer.
(async()=>{
 const result=await build({stdin:{contents:`
 import * as THREE from 'three';
 import {createBoatModel} from './boat-model.mjs';
 import {createBoatAccessories,DEFAULT_ACCESSORIES,accessoryCatalog} from './boat-accessories.mjs';
 import {createShipCustomization} from './ship-customization.mjs';
 const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setSize(1200,900);renderer.setPixelRatio(1);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.setClearColor('#edf2f3');renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;document.body.append(renderer.domElement);
 const scene=new THREE.Scene(),camera=new THREE.OrthographicCamera(-2.5,2.5,1.875,-1.875,.1,50);scene.add(new THREE.HemisphereLight('#fff6df','#8696aa',2.3));const sun=new THREE.DirectionalLight('#fff2db',3.1);sun.position.set(-3,7,5);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-4;sun.shadow.camera.right=4;sun.shadow.camera.top=4;sun.shadow.camera.bottom=-4;sun.shadow.normalBias=.02;scene.add(sun);scene.add(new THREE.AmbientLight('#e4f0ff',.4));
 const ground=new THREE.Mesh(new THREE.PlaneGeometry(30,30),new THREE.MeshStandardMaterial({color:'#edf2f3',roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-.145;ground.receiveShadow=true;scene.add(ground);
 const boat=createBoatModel();boat.materials.glass.emissiveIntensity=0;scene.add(boat.ship);const custom=createShipCustomization(boat.ship,boat.materials,()=>{},{name:'晚风号'},()=>true,boat);
 window.review=(skin,items={},view='hero')=>{custom.update({skinId:skin,accessories:{...DEFAULT_ACCESSORIES,deck:'polar-bear',roof:null,charm:'dolphin-charm',...items}},{save:false});custom.animate(0);boat.ship.position.set(0,0,0);camera.position.set(...(view==='top'?[0,9,.001]:view==='side'?[-7,1.2,0]:[-4.5,3.1,5.2]));camera.lookAt(0,.95,0);camera.zoom=view==='top'?1.18:1.06;camera.updateProjectionMatrix();renderer.render(scene,camera);return renderer.info.memory;};
 window.items=accessoryCatalog.filter(a=>a.thumb);
 window.single=(id,detail=false)=>{
  renderer.setSize(600,450);renderer.setScissorTest(false);renderer.setClearColor('#edf2f3');boat.ship.visible=true;ground.visible=true;camera.left=-2.5;camera.right=2.5;camera.top=1.875;camera.bottom=-1.875;
  const item=window.items.find(a=>a.id===id),slot=item.slots[0];window.review('classic',{deck:null,roof:null,charm:null,lifering:null,[slot]:id});
  if(detail){boat.ship.visible=false;ground.visible=false;const fitting=boat.mounts[slot].children[0].clone(true);fitting.position.set(0,0,0);fitting.rotation.set(0,0,0);fitting.scale.setScalar(1);scene.add(fitting);const bounds=new THREE.Box3().setFromObject(fitting),size=bounds.getSize(new THREE.Vector3());fitting.position.sub(bounds.getCenter(new THREE.Vector3()));const extent=Math.max(size.x,size.y,size.z)*.79;camera.left=-extent;camera.right=extent;camera.top=extent*.75;camera.bottom=-extent*.75;camera.zoom=1;camera.position.set(...(slot==='flag'?[-5,2,2]:[2,1.2,5]));camera.lookAt(0,0,0);camera.updateProjectionMatrix();renderer.render(scene,camera);scene.remove(fitting);}
 };
 window.gallery=()=>{
  boat.ship.visible=false;ground.visible=false;const items=window.items,models=[];renderer.setSize(1440,540);renderer.setScissorTest(true);
  items.forEach((item,i)=>{const model=createBoatModel(),fittings=createBoatAccessories(model),slot=item.slots[0];fittings.apply({...DEFAULT_ACCESSORIES,[slot]:item.id});const source=model.mounts[slot].children[0],group=source.clone(true);group.position.set(0,0,0);group.rotation.set(0,0,0);group.scale.setScalar(1);scene.add(group);const bounds=new THREE.Box3().setFromObject(group),center=bounds.getCenter(new THREE.Vector3()),size=bounds.getSize(new THREE.Vector3());group.position.sub(center);const extent=Math.max(size.x,size.y,size.z)*.75;camera.left=-extent;camera.right=extent;camera.top=extent*.75;camera.bottom=-extent*.75;camera.zoom=1;camera.position.set(...(slot==='flag'?[-5,2,2]:[2,1.2,5]));camera.lookAt(0,0,0);camera.updateProjectionMatrix();const x=i%6*240,y=540-(Math.floor(i/6)+1)*180;renderer.setViewport(x,y,240,180);renderer.setScissor(x,y,240,180);renderer.setClearColor(i%2?'#edf2f3':'#f7f7f1');renderer.render(scene,camera);group.visible=false;models.push(model);});
  return items.map(i=>i.name);
 };
 window.review('classic');`,resolveDir:process.cwd(),sourcefile:'model-review-entry.js'},bundle:true,format:'iife',write:false});
 const file=path.resolve('qa/model-review.html');await fs.writeFile(file,'<!doctype html><meta charset="utf-8"><style>body{margin:0}canvas{display:block}</style><body><script>'+result.outputFiles[0].text.replaceAll('</script','<\\/script')+'</script>');
 const browser=await chromium.launch({channel:'msedge',headless:true});
 try{
  const page=await browser.newPage({viewport:{width:1200,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('file:///'+file.replaceAll('\\','/'));await page.waitForFunction(()=>window.review);
  for(const view of ['hero','side','top']){await page.evaluate(v=>window.review('classic',{},v),view);await page.screenshot({path:'qa/remodel-'+view+'.png'});}
  const items=await page.evaluate(()=>window.items);await fs.mkdir('qa/fidelity',{recursive:true});await page.setViewportSize({width:600,height:450});
  for(const item of items)for(const detail of [false,true]){await page.evaluate(({id,detail})=>window.single(id,detail),{id:item.id,detail});await page.screenshot({path:'qa/fidelity/'+item.id+(detail?'-detail':'-boat')+'.png'});}
  await page.setViewportSize({width:1440,height:540});const names=await page.evaluate(()=>window.gallery());await page.screenshot({path:'qa/remodel-accessories.png'});
  const codes=['A1','A2','A4','A5','A6','A9','B1','B2','B3','B4','B5','B6','B7','B8','B9','C1','D1','D5'];
  await fs.writeFile('qa/fidelity-review.html','<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>饰品 · 实际模型对照</title><meta name="viewport" content="width=device-width"><style>body{margin:32px auto;max-width:1200px;padding:0 20px;color:#33485c;background:#f7f8f6;font:16px/1.65 system-ui}h1{font-size:27px}article{background:white;border:1px solid #dde5e8;border-radius:16px;margin:22px 0;padding:20px}h2{margin:0 0 12px;font-size:19px}.views{display:grid;grid-template-columns:130px 1fr 1.4fr;gap:16px;align-items:center}figure{margin:0;text-align:center}img{width:100%;border-radius:10px}.reference{width:80px;height:150px;background-image:url(../assets/boat-accessories.png);margin:0 auto}figcaption{color:#718291;font-size:13px}a{color:#326a94}@media(max-width:700px){.views{grid-template-columns:80px 1fr}.boat{grid-column:1/-1}}</style><h1>饰品 · 参考与实际模型</h1><p>左：原始饰品表；中：当前生产代码的模型近景；右：同一经典船上的实际安装效果。不是生成的候选图。点击图片可放大。</p><p><a href="fidelity-before.png">改动前模型</a> · <a href="remodel-accessories.png">当前全部 18 件</a> · <a href="../history/references/boat-placement-v01.md">装船候选图说明</a></p>'+
   items.map((a,i)=>'<article><h2>'+codes[i]+' · '+a.name+'</h2><div class="views"><figure><div class="reference" style="background-position:-'+a.thumb[0]+'px -'+a.thumb[1]+'px"></div><figcaption>原始参考</figcaption></figure><figure><a href="fidelity/'+a.id+'-detail.png"><img alt="'+a.name+'实际模型" src="fidelity/'+a.id+'-detail.png"></a><figcaption>实际模型近景</figcaption></figure><figure class="boat"><a href="fidelity/'+a.id+'-boat.png"><img alt="'+a.name+'装船效果" src="fidelity/'+a.id+'-boat.png"></a><figcaption>经典船 · 实际比例与安装位置</figcaption></figure></div></article>').join('')+'</html>');
  if(errors.length)throw Error(errors.join('\n'));console.log(JSON.stringify({rendered:items.length,installed:items.length,order:names,errors}));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
