const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs/promises');
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 try{
  const page=await browser.newPage({viewport:{width:1100,height:800}}),errors=[];
  page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{window.oceanTools={};Object.defineProperty(document,'modelContext',{value:{registerTool:t=>window.oceanTools[t.name]=t}});if(!localStorage.getItem('tiny-tides-game-debug-v1'))localStorage.setItem('tiny-tides-game-debug-v1',JSON.stringify({version:8,shipCustomization:{name:'晚风号',equippedBadge:'whale'},ownedBadges:[{badgeId:'whale'}],sailingData:{points:128,totalSailingSeconds:7680}}));});
  await page.goto('http://127.0.0.1:4173/?sailingDebug=fast');await page.waitForFunction(()=>document.querySelector('#loading').hidden);await page.locator('#scene').focus();await page.keyboard.press('Enter');await page.waitForTimeout(1100);
  const state=()=>page.evaluate(()=>window.oceanTools.get_ocean_state.execute({}));
  assert.deepEqual(await page.locator('.ship-tabs [role=tab]').allTextContents(),['船体','装饰']);
  assert.match(await page.locator('#ship-balance').textContent(),/128\s*海里/);
  await page.locator('#ship-name-edit').click();await page.locator('#ship-name').fill('晨光号');await page.keyboard.press('Enter');assert.equal((await state()).shipCustomization.name,'晨光号');assert.equal(await page.locator('#journal-cover-name').textContent(),'晨光号');
  await page.locator('#ship-name-edit').click();await page.locator('#ship-name').fill('取消名称');await page.keyboard.press('Escape');assert.equal((await state()).shipCustomization.name,'晨光号');assert.equal(await page.locator('#my-ship').isVisible(),true);
  await page.locator('#ship-name-edit').click();await page.locator('#ship-name').fill('海风号');await page.locator('#ship-balance').click();assert.equal((await state()).shipCustomization.name,'海风号');assert.equal(await page.locator('#mileage-info').getAttribute('aria-hidden'),'false');assert.match(await page.locator('#mileage-info').textContent(),/1 分钟.*1 海里/);
  await page.waitForTimeout(200);await page.screenshot({path:'qa/showcase-mileage.png'});await page.mouse.click(1000,400);assert.equal(await page.locator('#mileage-info').getAttribute('aria-hidden'),'true');
  await page.locator('#tab-accessories').click();await page.locator('#decoration-category').selectOption('badges');assert.equal(await page.locator('#ship-badges').isVisible(),true);await page.locator('.ship-badge').first().click();assert.equal(await page.locator('#journal-cover-badge').isVisible(),false);
  await page.locator('#tab-skins').click();await page.screenshot({path:'qa/showcase-identity-wide.png'});
  const before=await state();await page.mouse.move(650,260);await page.mouse.wheel(0,-200);await page.waitForTimeout(250);assert.ok((await state()).showcase.zoom<before.showcase.zoom);assert.ok((await state()).travelTime>before.travelTime);
  for(const size of [{width:1100,height:800},{width:560,height:540},{width:390,height:700}]){
   await page.setViewportSize(size);await page.waitForTimeout(350);const cover=await page.locator('#journal-open').boundingBox(),panel=await page.locator('#ship-panel').boundingBox();assert.ok(cover.x>=0&&cover.y>=0&&cover.y+cover.height<panel.y-5,JSON.stringify({size,cover,panel}));assert.ok(cover.height>=45&&cover.height<=125);
   assert.equal(await page.locator('#ship-panel').evaluate(e=>e.scrollWidth<=e.clientWidth),true);await page.screenshot({path:`qa/showcase-identity-${size.width}.png`});
   if(size.width<=650){await page.locator('#ship-balance').click();await page.waitForTimeout(200);assert.ok((await page.locator('#mileage-info').boundingBox()).y>=panel.y,'narrow mileage explanation belongs over the panel, away from the boat');await page.keyboard.press('Escape');}
  }
  await page.evaluate(()=>window.emitWorldEvent('encounter_completed',{encounterId:'pink_dolphin',startTime:'2026-09-20T10:00:00Z',endTime:'2026-09-20T10:00:30Z',shipName:'旧船名',weather:'clear',timeOfDay:'day',firstTime:true,seenCount:1}));
  assert.equal(await page.locator('#journal-unread').isVisible(),true);await page.evaluate(()=>window.originalCover=document.querySelector('.book-cover'));await page.locator('#journal-open').click();await page.waitForTimeout(450);await page.screenshot({path:'qa/showcase-book-opening.png'});await page.waitForTimeout(850);assert.equal(await page.evaluate(()=>window.originalCover===document.querySelector('.book-cover')),true);assert.equal(await page.locator('.book-cover').count(),1);assert.match(await page.locator('.left-page').textContent(),/旧船名/);assert.equal(await page.locator('#journal-unread').isVisible(),false);
  const openBox=await page.locator('.journal-book').boundingBox();await page.keyboard.press('Escape');await page.waitForTimeout(680);const closingBox=await page.locator('.journal-book').boundingBox();assert.ok(closingBox.width<openBox.width*.9,'narrow-window book must move back before closing completes');await page.waitForTimeout(400);assert.equal(await page.locator('#journal-open').evaluate(e=>e===document.activeElement),true);assert.equal(await page.locator('#journal-open').isVisible(),true);
  for(let i=0;i<28;i++){await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>getComputedStyle(document.activeElement).visibility),'visible');}
  await page.emulateMedia({reducedMotion:'reduce'});await page.locator('#journal-open').click();await page.waitForTimeout(140);assert.equal(await page.locator('.journal-book').evaluate(e=>getComputedStyle(e).transitionDuration.split(',')[0]),'0.09s');await page.keyboard.press('Escape');await page.waitForTimeout(140);
  await page.reload();await page.waitForFunction(()=>document.querySelector('#loading').hidden);assert.equal((await state()).shipCustomization.name,'海风号');assert.deepEqual(errors,[]);
  const result={checks:'two tabs / inline name Enter Escape outside save / mileage popover / nested badges / limited zoom / sailing continuity / book dock 3 sizes / same cover node / bookmark / legacy log name / visible keyboard focus / narrow close transition / reduced motion / reload',errors};await fs.writeFile('qa/showcase-layout-results.json',JSON.stringify(result,null,2)+'\n');console.log(result);
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
