const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),http=require('node:http');
(async()=>{
 const html=await fs.readFile('qa-preview/index.html'),server=http.createServer((req,res)=>res.setHeader('Content-Type','text/html').end(html));await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const browser=await chromium.launch({channel:'msedge',headless:true}),errors=[],checks=[];
 try{
  const page=await browser.newPage({viewport:{width:1100,height:800}});page.on('pageerror',e=>errors.push(e.message));
  await page.addInitScript(()=>{window.oceanTools={};Object.defineProperty(document,'modelContext',{value:{registerTool:t=>window.oceanTools[t.name]=t}});window.audioPlays=[];window.audioCreated=0;const OriginalAudio=Audio;window.Audio=function(...args){window.audioCreated++;return new OriginalAudio(...args);};window.Audio.prototype=OriginalAudio.prototype;const play=HTMLMediaElement.prototype.play;HTMLMediaElement.prototype.play=function(){window.audioPlays.push({at:performance.now(),volume:this.volume});return play.call(this);};});
  await page.goto(`http://127.0.0.1:${server.address().port}/?scenario=day`);await page.waitForFunction(()=>document.querySelector('#loading').hidden);await page.evaluate(()=>document.querySelector('#qa-panel').hidden=true);
  const state=()=>page.evaluate(()=>window.oceanTools.get_ocean_state.execute({})),saved=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('tiny-tides-game-v1')));
  const phase=async name=>page.waitForFunction(n=>document.querySelector('#journal').dataset.state===n,name);
  const open=async()=>{await page.locator('#journal-open').click();await phase('open');};const close=async()=>{await page.locator('#journal-close').click();await phase('closed');};
  const chapter=async id=>{await page.locator(`[data-chapter=${id}]`).click();await phase('open');};const next=async()=>{await page.locator('#journal-next').click();await phase('open');};
  const emit=async(id,count=1)=>page.evaluate(({id,count})=>{const at=new Date().toISOString();window.emitWorldEvent('encounter_completed',{encounterId:id,startTime:at,endTime:at,shipName:'小雨号',weather:'clear',timeOfDay:'day',firstTime:count===1,seenCount:count});},{id,count});
  assert.equal(await page.locator('#journal-open').isVisible(),true);assert.equal(await page.locator('#my-ship').count(),0);await page.locator('#scene').focus();await page.keyboard.press('Enter');assert.equal((await state()).journalBook.phase,'closed');
  await page.screenshot({path:'qa/unified-dock.png'});const original=await state(),dock=await page.locator('#journal-open').boundingBox();await open();await page.waitForTimeout(1200);const reading=await state();assert.equal(reading.boatSize,.75);assert.deepEqual(reading.camera,original.camera);assert.ok(reading.travelTime>original.travelTime+1);assert.equal(reading.isSailingActive,true);assert.equal(reading.rendererCount,1);
  await page.locator('[aria-label="编辑船名"]').click();await page.locator('#ship-name').fill('星海号');await page.keyboard.press('Enter');assert.equal((await state()).shipCustomization.name,'星海号');await page.locator('[aria-label="编辑船名"]').click();await page.locator('#ship-name').fill('取消');await page.keyboard.press('Escape');assert.equal((await state()).shipCustomization.name,'星海号');assert.equal((await state()).journalBook.phase,'open');
  await page.locator('#ship-balance').click();assert.match(await page.locator('.mileage-note').innerText(),/1 分钟航行 = 1 海里/);await page.locator('.model-name').click();assert.equal(await page.locator('.mileage-note').isVisible(),false);
  const model=page.locator('.right-page .journal-ship-model');await model.focus();await page.keyboard.press('ArrowRight');assert.notEqual((await state()).journalBook.preview.yaw,reading.journalBook.preview.yaw);assert.deepEqual((await state()).camera,original.camera);await page.screenshot({path:'qa/unified-profile.png'});checks.push('persistent single book; ship click removed; 75% sailing and camera unchanged; inline name Enter/Escape; mileage; independent preview rotation');
  await next();assert.equal(await page.locator('.left-page [data-skin]').count(),9);await page.locator('.left-page [data-skin=gentle]').click();await page.waitForTimeout(1200);assert.equal((await state()).shipCustomization.skinId,'gentle');assert.equal((await saved()).journalAnnotations.length,1);assert.equal((await saved()).sailingData.points,0);
  const pixels=await page.locator('.right-page canvas').evaluate(c=>[...c.getContext('2d').getImageData(0,0,320,320).data].filter((v,i)=>i%4===3&&v>0).length);assert.ok(pixels>2000,'customization model renders');assert.equal(await page.locator('[data-accessory=pink-dolphin]').count(),0);await page.screenshot({path:'qa/unified-customization.png'});checks.push('nine free skins and live shared preview; unknown ornaments hidden; annotation retained');
  await close();const returned=await page.locator('#journal-open').boundingBox();assert.ok(Math.abs(returned.x-dock.x)<1&&Math.abs(returned.y-dock.y)<1);await emit('giant_whale_shadow');assert.equal(await page.locator('#journal-unread').isVisible(),true);await open();await chapter('voyage');const choices=page.locator('.left-page .intent-sentence,.right-page .intent-sentence');assert.equal(await choices.count(),3);await choices.first().hover();await page.screenshot({path:'qa/unified-voyage.png'});
  await choices.first().click();await phase('writing');await page.locator('.journal-backdrop').click({position:{x:10,y:10}});assert.equal((await state()).journalBook.queuedClose,true);await phase('drawing');await page.waitForTimeout(50);assert.equal(await page.locator('#journal-pencil').isVisible(),true);const offset=await page.locator('.left-page [data-kind=doodle] path,.right-page [data-kind=doodle] path').first().evaluate(n=>Number(n.style.strokeDashoffset));assert.ok(offset>0);await page.screenshot({path:'qa/unified-drawing.png'});await phase('closed');assert.equal((await saved()).journalEntries[0].selectedIntentId,'follow_deep_creature');checks.push('new clue bookmark; prose choice; character writing then SVG drawing; backdrop close waits; choice survives');
  // Exercise long paragraphs using a test-only save, preserving the existing historical name.
  await page.addInitScript(()=>{if(sessionStorage.getItem('long-paper'))return;sessionStorage.setItem('long-paper','1');const key='tiny-tides-game-v1',s=JSON.parse(localStorage.getItem(key));s.journalEntries[0].body='海风吹过甲板，小船在海上慢慢向前。'.repeat(45);localStorage.setItem(key,JSON.stringify(s));});await page.reload();await page.waitForFunction(()=>document.querySelector('#loading').hidden);await page.evaluate(()=>document.querySelector('#qa-panel').hidden=true);await open();await chapter('ship');
  for(const viewport of [{width:560,height:540},{width:390,height:700}]){await page.setViewportSize(viewport);await page.waitForTimeout(400);await page.screenshot({path:`qa/unified-profile-${viewport.width}.png`});await next();assert.equal(await page.locator('.left-page [data-skin]').count(),9);await page.locator('.left-page [data-skin=classic]').scrollIntoViewIfNeeded();await chapter('voyage');await page.screenshot({path:`qa/unified-voyage-${viewport.width}.png`});const bounds=await page.locator('.journal-book').boundingBox();assert.ok(bounds.x>=0&&bounds.x+bounds.width<viewport.width);await chapter('ship');}
  await page.setViewportSize({width:1100,height:800});await page.waitForTimeout(300);await next();await next();let prose='';for(let guard=0;guard<30;guard++){const result=await page.locator('.left-page .journal-content,.right-page .journal-content').evaluateAll(nodes=>nodes.map(n=>({overflow:n.scrollHeight>n.clientHeight+2,text:[...n.querySelectorAll('.journal-prose')].map(p=>p.textContent).join('')})));assert.ok(result.every(r=>!r.overflow),'no log content clipped');prose+=result.map(r=>r.text).join('');if(await page.locator('#journal-next').isDisabled())break;await next();}assert.equal(prose,(await saved()).journalEntries[0].body.replaceAll('\n',''));checks.push('actual measured pagination retains long text; 560/390 widths and chapter navigation');
  await close();await page.locator('#edit').click();if((await state()).audio.requested)await page.locator('#sound').click();const audioBefore=await page.evaluate(()=>window.audioPlays.length);await open();await chapter('ship');await page.waitForTimeout(300);await close();assert.equal(await page.evaluate(()=>window.audioPlays.length),audioBefore);checks.push('journal respects mute');
  await page.emulateMedia({reducedMotion:'reduce'});await open();await chapter('ship');await page.waitForTimeout(6000);const cdp=await page.context().newCDPSession(page);await cdp.send('HeapProfiler.collectGarbage');const audioCount=await page.evaluate(()=>window.audioCreated),warm=await state();await close();const baseline=await page.evaluate(()=>document.querySelectorAll('*').length);
  for(let i=0;i<30;i++){await open();await close();}await open();await page.waitForTimeout(6000);await cdp.send('HeapProfiler.collectGarbage');const after=await state();assert.equal(await page.evaluate(()=>window.audioCreated),audioCount);await close();assert.ok((await page.evaluate(()=>document.querySelectorAll('*').length))<=baseline+2);assert.equal(after.last.geometries,warm.last.geometries);assert.equal(after.last.textures,warm.last.textures);assert.equal(await page.locator('.journal-book').count(),1);checks.push('30 reduced-motion open/close cycles: stable DOM, Audio instances, geometries and textures');
  await emit('giant_whale_surface');await open();await chapter('voyage');assert.match(await page.locator('.left-page').innerText(),/原来是它/);const art=page.locator('.right-page [data-kind=doodle]');assert.ok((await art.boundingBox()).height>150);await page.screenshot({path:'qa/unified-whale-spread.png'});await page.keyboard.press('Escape');await phase('closed');checks.push('important whale encounter owns a full spread; keyboard Escape works after chapter jump');
  assert.deepEqual(errors,[]);const result={date:new Date().toISOString(),checks,errors,resources:{before:warm.last,after:after.last}};await fs.writeFile('qa/unified-journal-results.json',JSON.stringify(result,null,2)+'\n');console.log(result);
 }finally{await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
